### ISSUE TITLE
Proposal to replace BurntSushi/toml

### ISSUE THREAD

**Issue by githubjeka** [go-ozzo/config#2]
`BurntSushi/toml` compatible with TOML version v0.2.0 only
[Latest TOML tagged version: v0.4.0.](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md)

I have used successfully. https://github.com/naoina/toml

**Comment by qiangxue** [comment]
Unfortunately `naoina/toml` requires a predefined struct to load the configuration, while ozzo-config is based on a free-form configuration structure.
