### ISSUE TITLE
Debugging ozzo-config.Config

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/config#5]
I builded a windows version of dalve and plugin that support it.
But when I debugging my App, i don't see any values loaded into this struct...

``` Go
func LoadConfig() *config.Config{
    // Load config
    c := config.New()
    c.Load("conf/config.json")
    return c
}
```

```
{
  "Version": "1.0",
  "StaticServer": {
    "Path": "./static"
  },
  "WebServer": {
    "PortHTTP": "8080",
    "PortHTTPS": "8088",
    "Domain": "localhost"
  },
  "Logger": {
    "Filename": "app.log",
    "Email": "****@gmail.com"
  },
  "Db":{
    "Type": "mysql",
    "Host": "localhost",
    "DbName": "inframe",
    "Login": "root",
    "Password": ""
  }
}
```

![image](https://cloud.githubusercontent.com/assets/3740898/12081741/e00e9e8a-b294-11e5-81a4-0b9d2f8f600a.png)
Are you see the same on Mac or more?

**Comment by qiangxue** [comment]
This is expected since Config stores the configuration content as a reflect.Value. I don't have a good solution to help inspect the loaded config content...

**Comment by kolkov** [comment]
I think we need to call @ignatov to solve this.
