### ISSUE TITLE
Can ozzo-Config Support Array?

### ISSUE THREAD

**Issue by bestony** [go-ozzo/config#7]
```
{
    "com": [
        "foo",
        "bar"
    ]
}
```
How to Deal this Data in JSON File?

**Comment by zuoRambo** [comment]
good question

**Comment by qiangxue** [comment]
Take a look at this test: https://github.com/go-ozzo/ozzo-config/blob/master/config_test.go#L25

**Comment by zuoRambo** [comment]
looks like `jsonpreprocess`support Array @bestony please close this issue~

**Comment by bestony** [comment]
Thanks For Reply!
